using System.Globalization;

namespace RuskaTrupa.Web.Localization;

public sealed class CultureState
{
    public CultureState()
    {
        SetCulture("bg");
    }

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["ActionLog"] = "Actions",
        ["Ai"] = "AI",
        ["AnnounceMarriage"] = "Announce marriage",
        ["AppName"] = "Ruska Trupa",
        ["AutoplayHand"] = "Autoplay",
        ["Bid"] = "Bid",
        ["BidMarriageChooseSuitError"] = "Choose which K+Q suit supports this bid.",
        ["BidMarriageRequiredError"] = "Bids above 120 require a K+Q pair in one suit.",
        ["BidMarriageSuit"] = "K+Q suit",
        ["Bidding"] = "Bidding",
        ["Bot1"] = "Player 1",
        ["Bot2"] = "Player 2",
        ["BotSkill"] = "Trick-play skill",
        ["Bidder"] = "Bidder",
        ["Bonuses"] = "Bonuses",
        ["Cards"] = "cards",
        ["Cancel"] = "Cancel",
        ["ChooseTrump"] = "Choose trump",
        ["ChooseCardFor"] = "Choose card for",
        ["ClearSavedGame"] = "Clear save",
        ["Close"] = "Close",
        ["ConfirmNewGame"] = "Start a new game? The current unfinished game will be replaced.",
        ["ConfirmAutoplayHand"] = "Autoplay the rest of this hand?",
        ["Contract"] = "Contract",
        ["ContractSuccess"] = "Contract made!",
        ["Continue"] = "Continue",
        ["ContinueGame"] = "Continue game",
        ["ContractProgress"] = "Contract progress",
        ["CompletedTricks"] = "Completed tricks",
        ["CurrentPhase"] = "Current phase",
        ["CurrentPlayer"] = "Current player",
        ["CurrentScore"] = "Current score",
        ["CurrentTrick"] = "Current trick",
        ["GuideBidding"] = "Choose a bid or pass.",
        ["GuideChooseTrump"] = "Choose the trump suit.",
        ["GuideGameOver"] = "The game is complete.",
        ["GuidePassCards"] = "Choose a card to pass.",
        ["GuidePlayingTricks"] = "Play one of the highlighted legal cards.",
        ["GuideRevealTalon"] = "Reveal the talon and add it to your hand.",
        ["GuideScoringHand"] = "Review the hand result, then settle the hand.",
        ["Gave"] = "gave",
        ["Deal"] = "Deal",
        ["Dealer"] = "Dealer",
        ["Deck"] = "Deck",
        ["EngineStatus"] = "Engine status",
        ["GameOver"] = "Game over",
        ["GameWinnerAnnouncement"] = "We have a winner",
        ["GameDetails"] = "Game details",
        ["GameMode"] = "Offline card game",
        ["GameSetup"] = "Game setup",
        ["GameSubtitle"] = "Play against two built-in opponents. Your progress is saved on this device.",
        ["GameTable"] = "Game table",
        ["Hand"] = "Hand",
        ["HandScore"] = "Hand score",
        ["HandSummary"] = "Hand summary",
        ["LastHand"] = "Last hand",
        ["Last"] = "Move to end",
        ["LastTrick"] = "Last trick",
        ["LegalCards"] = "Legal cards",
        ["HumanPlayer"] = "You",
        ["Language"] = "Language",
        ["LoadSavedGame"] = "Load saved game",
        ["LoadingGame"] = "Loading game...",
        ["MarriagePromptDefault"] = "Default: yes after 2 seconds",
        ["NewDeal"] = "New deal",
        ["NewGame"] = "New game",
        ["NewGameSetup"] = "New game",
        ["Next"] = "Next",
        ["No"] = "No",
        ["NoBid"] = "None",
        ["NoTrump"] = "no trump",
        ["NoTrumpShort"] = "NT",
        ["NotSelected"] = "Not selected",
        ["OpponentOne"] = "Opponent 1",
        ["OpponentTwo"] = "Opponent 2",
        ["OpponentName"] = "Name",
        ["Pass"] = "Pass",
        ["PassCards"] = "Pass cards",
        ["PassTo"] = "Pass to",
        ["PlayingTricks"] = "Playing tricks",
        ["PlayOn"] = "Let's start",
        ["PlayAgain"] = "Play again",
        ["PlayStyle"] = "Bidding style",
        ["PlaySpeed"] = "Play speed",
        ["PlayableNow"] = "Playable now",
        ["Points"] = "pts",
        ["Previous"] = "Previous",
        ["RevealTalon"] = "Reveal talon",
        ["Replay"] = "Review",
        ["ReplayStart"] = "Start of hand",
        ["ReviewHand"] = "Review game",
        ["ExitReplay"] = "Exit review",
        ["First"] = "Move to start",
        ["ResignHand"] = "Resign hand",
        ["Rules"] = "Rules",
        ["ScoreDelta"] = "Score delta",
        ["ScoringHand"] = "Scoring hand",
        ["Seed"] = "Seed",
        ["SettleHand"] = "Enter result",
        ["StartGame"] = "Start game",
        ["SaveStatus"] = "Save status",
        ["SavedLocally"] = "Auto-saved locally",
        ["SignalTrupa"] = "Trupa",
        ["SignalTrupaHint"] = "Ask your partner to put points in this trick",
        ["TableCenter"] = "Table",
        ["Talon"] = "Talon",
        ["TargetScore"] = "Target",
        ["To"] = "to",
        ["Trump"] = "Trump",
        ["Winner"] = "Winner",
        ["Yes"] = "Yes",
        ["YourName"] = "Your name",
        ["YourTurnToBid"] = "Your bid?",
        ["YourHand"] = "Your hand"
    };

    private static readonly IReadOnlyDictionary<string, string> Bulgarian = new Dictionary<string, string>
    {
        ["ActionLog"] = "Действия",
        ["Ai"] = "ИИ",
        ["AnnounceMarriage"] = "Обяви брак",
        ["AppName"] = "Руска Трупа",
        ["AutoplayHand"] = "Доиграй сам",
        ["Bid"] = "Анонс",
        ["BidMarriageChooseSuitError"] = "Избери от коя боя имаш K+Q.",
        ["BidMarriageRequiredError"] = "За анонс над 120 трябва да имаш поп и дама в една боя.",
        ["BidMarriageSuit"] = "Боя с K+Q",
        ["Bidding"] = "Наддаване",
        ["Bot1"] = "Играч 1",
        ["Bot2"] = "Играч 2",
        ["BotSkill"] = "Умение в разиграването",
        ["Bidder"] = "Анонсьор",
        ["Bonuses"] = "Бонуси",
        ["Cards"] = "карти",
        ["Cancel"] = "Отказ",
        ["ChooseTrump"] = "Избор на коз",
        ["ChooseCardFor"] = "Избери карта за",
        ["ClearSavedGame"] = "Изтрий запис",
        ["Close"] = "Затвори",
        ["ConfirmNewGame"] = "Да започне ли нова игра? Текущата незавършена игра ще бъде заменена.",
        ["ConfirmAutoplayHand"] = "Да доиграе ли ботът тази ръка вместо теб?",
        ["Contract"] = "Договор",
        ["ContractSuccess"] = "Браво, изкара анонса!",
        ["Continue"] = "Продължи",
        ["ContinueGame"] = "Продължи игра",
        ["ContractProgress"] = "Напредък по договора",
        ["CompletedTricks"] = "Изиграни взятки",
        ["CurrentPhase"] = "Текуща фаза",
        ["CurrentPlayer"] = "На ход",
        ["CurrentScore"] = "Текущ резултат",
        ["CurrentTrick"] = "Текуща взятка",
        ["GuideBidding"] = "Избери анонс или пас.",
        ["GuideChooseTrump"] = "Избери коз.",
        ["GuideGameOver"] = "Играта приключи.",
        ["GuidePassCards"] = "Избери карта за даване.",
        ["GuidePlayingTricks"] = "Играй една от маркираните позволени карти.",
        ["GuideRevealTalon"] = "Покажи талона и го добави към ръката.",
        ["GuideScoringHand"] = "Прегледай резултата, после приключи ръката.",
        ["Gave"] = "даде",
        ["Deal"] = "Раздаване",
        ["Dealer"] = "Раздаващ",
        ["Deck"] = "Тесте",
        ["EngineStatus"] = "Състояние на играта",
        ["GameOver"] = "Край на играта",
        ["GameWinnerAnnouncement"] = "Имаме победител",
        ["GameDetails"] = "Детайли за играта",
        ["GameMode"] = "Офлайн игра с карти",
        ["GameSetup"] = "Настройки на играта",
        ["GameSubtitle"] = "Играй срещу двама вградени опоненти. Напредъкът се запазва на това устройство.",
        ["GameTable"] = "Маса",
        ["Hand"] = "Ръка",
        ["HandScore"] = "Резултат в ръката",
        ["HandSummary"] = "Обобщение на ръката",
        ["LastHand"] = "Последна ръка",
        ["Last"] = "Премести в края",
        ["LastTrick"] = "Последна взятка",
        ["LegalCards"] = "Позволени карти",
        ["HumanPlayer"] = "Ти",
        ["Language"] = "Език",
        ["LoadSavedGame"] = "Зареди игра",
        ["LoadingGame"] = "Зареждане...",
        ["MarriagePromptDefault"] = "По подразбиране: да след 2 секунди",
        ["NewDeal"] = "Ново раздаване",
        ["NewGame"] = "Нова игра",
        ["NewGameSetup"] = "Нова игра",
        ["Next"] = "Напред",
        ["No"] = "Не",
        ["NoBid"] = "Няма",
        ["NoTrump"] = "безкоз",
        ["NoTrumpShort"] = "БК",
        ["NotSelected"] = "Не е избран",
        ["OpponentOne"] = "Опонент 1",
        ["OpponentTwo"] = "Опонент 2",
        ["OpponentName"] = "Име",
        ["Pass"] = "Пас",
        ["PassCards"] = "Даване на карти",
        ["PassTo"] = "Дай на",
        ["PlayingTricks"] = "Игра на взятки",
        ["PlayOn"] = "Да започваме",
        ["PlayAgain"] = "Да играем пак",
        ["PlayStyle"] = "Стил на наддаване",
        ["PlaySpeed"] = "Скорост на игра",
        ["PlayableNow"] = "Можеш да играеш",
        ["Points"] = "т.",
        ["Previous"] = "Назад",
        ["RevealTalon"] = "Покажи талона",
        ["Replay"] = "Преглед",
        ["ReplayStart"] = "Начало на ръката",
        ["ReviewHand"] = "Прегледай играта",
        ["ExitReplay"] = "Изход",
        ["First"] = "Премести в началото",
        ["ResignHand"] = "Откажи ръката",
        ["Rules"] = "Правила",
        ["ScoreDelta"] = "Промяна",
        ["ScoringHand"] = "Точкуване",
        ["Seed"] = "Seed",
        ["SettleHand"] = "Впиши резултата",
        ["StartGame"] = "Започни игра",
        ["SaveStatus"] = "Запис",
        ["SavedLocally"] = "Запазва се локално",
        ["SignalTrupa"] = "Трупай",
        ["SignalTrupaHint"] = "Поискай от партньора да вкара точки в тази взятка",
        ["TableCenter"] = "Маса",
        ["Talon"] = "Талон",
        ["TargetScore"] = "Цел",
        ["To"] = "на",
        ["Trump"] = "Коз",
        ["Winner"] = "Победител",
        ["Yes"] = "Да",
        ["YourName"] = "Твоето име",
        ["YourTurnToBid"] = "Твоят анонс?",
        ["YourHand"] = "Твоите карти"
    };

    public IReadOnlyList<CultureInfo> SupportedCultures { get; } =
        new[] { new CultureInfo("bg"), new CultureInfo("en") };

    public CultureInfo CurrentCulture => CultureInfo.CurrentUICulture;

    public string this[string key]
    {
        get
        {
            var source = CurrentCulture.TwoLetterISOLanguageName == "bg" ? Bulgarian : English;
            return source.TryGetValue(key, out var value) ? value : key;
        }
    }

    public void SetCulture(string cultureName)
    {
        var culture = SupportedCultures.FirstOrDefault(candidate => candidate.Name == cultureName)
            ?? SupportedCultures[0];

        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
    }
}
